Repository thetacola/Susquehanna, pull requests merged in 2024-12, with the labels that each got.

#24 Fix issues found by PMD
  .settings/.gitignore
  pom.xml
  src/main/java/net/oijon/susquehanna/App.java
  src/main/java/net/oijon/susquehanna/Launcher.java
  src/main/java/net/oijon/susquehanna/LoadingScreen.java
  src/main/java/net/oijon/susquehanna/SystemInfo.java
  src/main/java/net/oijon/susquehanna/gui/components/BinderTab.java
  src/main/java/net/oijon/susquehanna/gui/components/OrthoList.java
  src/main/java/net/oijon/susquehanna/gui/components/PhonemeKeyboard.java
  src/main/java/net/oijon/susquehanna/gui/components/PhonemeTable.java
  src/main/java/net/oijon/susquehanna/gui/components/ToolButton.java
  src/main/java/net/oijon/susquehanna/gui/scenes/file/InfoPage.java
  src/main/java/net/oijon/susquehanna/gui/scenes/file/OpenLangPage.java
  src/main/java/net/oijon/susquehanna/gui/scenes/lexicon/EditWordsPage.java
  src/main/java/net/oijon/susquehanna/gui/scenes/phonology/EditPhonoPage.java
  src/main/java/net/oijon/susquehanna/gui/scenes/phonology/ViewPhonoPage.java
Labels: enhancement

#25 17 prevent ortholist from scrambling orthography
  pom.xml
  src/main/java/net/oijon/susquehanna/SystemInfo.java
  src/main/java/net/oijon/susquehanna/gui/components/OrthoList.java
Labels: bug

#29 cleaned up files
  .logo-48.png-autosave.kra
  dependency-reduced-pom.xml
  logo-48.png~
  logo.png~
  src/main/resources/img/bar-template.pdn
  src/main/resources/img/empty-bar.png~
  src/main/resources/img/left-papers.png-autosave.kra
  src/main/resources/img/tab-template.pdn
Labels: enhancement

#31 30 create manual for susquehanna
  README.md
  manual/img/allophones.png
  manual/img/diagram.png
  manual/img/edit-orthography.png
  manual/img/edit-phonology.png
  manual/img/edit-words.png
  manual/img/file-tab.png
  manual/img/info.png
  manual/img/lexicon-tab.png
  manual/img/logo.png
  manual/img/new-language.png
  manual/img/open-language.png
  manual/img/orthography-tab.png
  manual/img/phonology-tab.png
  manual/img/phonotactics.png
  manual/img/report-bug.png
  manual/img/script.png
  manual/img/tabs-screenshot.png
  manual/img/view-orthography.png
  manual/img/view-phonology.png
  manual/img/view-words.png
  manual/manual.aux
  manual/manual.pdf
  manual/manual.synctex.gz
  manual/manual.tex
  manual/manual.toc
Labels: documentation

#33 23 fix issues found by pmd
  manual/manual.pdf
  manual/manual.synctex.gz
  manual/manual.tex
  src/main/java/net/oijon/susquehanna/Launcher.java
  src/main/java/net/oijon/susquehanna/gui/components/PhonemeButton.java
  src/main/java/net/oijon/susquehanna/gui/components/PhonemeEditPopup.java
  src/main/java/net/oijon/susquehanna/gui/resources/Backgrounds.java
  src/main/java/net/oijon/susquehanna/gui/resources/Fonts.java
  src/main/java/net/oijon/susquehanna/gui/resources/Indicator.java
  src/main/java/net/oijon/susquehanna/gui/scenes/BlankPage.java
  src/main/java/net/oijon/susquehanna/gui/scenes/file/AddLangPage.java
  src/main/java/net/oijon/susquehanna/gui/scenes/file/ReportBugPage.java
  src/main/java/net/oijon/susquehanna/gui/scenes/lexicon/ViewWordsPage.java
  src/main/java/net/oijon/susquehanna/gui/scenes/orthography/EditOrthographyPage.java
  src/main/java/net/oijon/susquehanna/gui/scenes/orthography/ViewOrthographyPage.java
Labels: enhancement
